services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    # volumes:
    #   - ./backend:/app
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
      - CORS_ALLOWED_ORIGIN=http://localhost:3000
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    # volumes:
    #   - ./frontend:/app
    ports:
      - 3000:3000
  db:
    image: "postgres:15-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    volumes:
      - db-store:/var/lib/postgresql/data

volumes:
  db-store:
