# .air.toml

# [build] セクションはビルドの設定を行います
[build]
# ビルドされたバイナリの出力先ファイル名
bin = "main"

# ビルドコマンドを指定。ここでは Go のビルドコマンドを設定しています。
cmd = "go build -o main ./cmd/main.go"

# 監視対象のファイルやディレクトリのパターンを指定
include = ["*.go"]

# 監視から除外するファイルやディレクトリのパターンを指定
exclude = ["assets/*", "tmp/*", "vendor/*", "testdata/*"]

# ビルドログに色を付けるかどうかを指定。デフォルトは true。
color = true

# ビルド時にターミナル画面をクリアするかどうかを指定。デフォルトは true。
clear = true

# [watch] セクションはファイルの監視に関する設定を行います
[watch]
# 監視から除外するファイルやディレクトリのパターンを指定
ignore = ["vendor/*"]

# ポーリングを使用してファイルの変更を検出するかどうかを指定。デフォルトは false。
poll = true

# ポーリングの間隔をミリ秒単位で指定。デフォルトは 1000 ミリ秒（1 秒）。
interval = 2000

# 詳細なログを出力するかどうかを指定。デフォルトは false。
verbose = true

# [server] セクションはサーバーの設定を行います（オプション）
[server]
# サーバーがリッスンするポートを指定。デフォルトは 8080。
port = 8080

# サーバーがバインドするアドレスを指定。デフォルトは "0.0.0.0"。
address = "0.0.0.0"

# サーバーのホスト名を指定。デフォルトは "localhost"。
host = "localhost"
