// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Next_Go_App/ent/menucategory"
	"Next_Go_App/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MenuCategoryDelete is the builder for deleting a MenuCategory entity.
type MenuCategoryDelete struct {
	config
	hooks    []Hook
	mutation *MenuCategoryMutation
}

// Where appends a list predicates to the MenuCategoryDelete builder.
func (mcd *MenuCategoryDelete) Where(ps ...predicate.MenuCategory) *MenuCategoryDelete {
	mcd.mutation.Where(ps...)
	return mcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mcd *MenuCategoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, mcd.sqlExec, mcd.mutation, mcd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (mcd *MenuCategoryDelete) ExecX(ctx context.Context) int {
	n, err := mcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mcd *MenuCategoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(menucategory.Table, sqlgraph.NewFieldSpec(menucategory.FieldID, field.TypeInt))
	if ps := mcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, mcd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	mcd.mutation.done = true
	return affected, err
}

// MenuCategoryDeleteOne is the builder for deleting a single MenuCategory entity.
type MenuCategoryDeleteOne struct {
	mcd *MenuCategoryDelete
}

// Where appends a list predicates to the MenuCategoryDelete builder.
func (mcdo *MenuCategoryDeleteOne) Where(ps ...predicate.MenuCategory) *MenuCategoryDeleteOne {
	mcdo.mcd.mutation.Where(ps...)
	return mcdo
}

// Exec executes the deletion query.
func (mcdo *MenuCategoryDeleteOne) Exec(ctx context.Context) error {
	n, err := mcdo.mcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{menucategory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mcdo *MenuCategoryDeleteOne) ExecX(ctx context.Context) {
	if err := mcdo.Exec(ctx); err != nil {
		panic(err)
	}
}
