// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Next_Go_App/ent/menucategory"
	"Next_Go_App/ent/user"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// MenuCategory is the model entity for the MenuCategory schema.
type MenuCategory struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MenuCategoryQuery when eager-loading is set.
	Edges        MenuCategoryEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MenuCategoryEdges holds the relations/edges for other nodes in the graph.
type MenuCategoryEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MenuCategoryEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MenuCategory) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case menucategory.FieldID, menucategory.FieldUserID:
			values[i] = new(sql.NullInt64)
		case menucategory.FieldName:
			values[i] = new(sql.NullString)
		case menucategory.FieldCreatedAt, menucategory.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MenuCategory fields.
func (mc *MenuCategory) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case menucategory.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			mc.ID = int(value.Int64)
		case menucategory.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				mc.UserID = int(value.Int64)
			}
		case menucategory.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				mc.Name = value.String
			}
		case menucategory.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				mc.CreatedAt = value.Time
			}
		case menucategory.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				mc.UpdatedAt = value.Time
			}
		default:
			mc.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MenuCategory.
// This includes values selected through modifiers, order, etc.
func (mc *MenuCategory) Value(name string) (ent.Value, error) {
	return mc.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the MenuCategory entity.
func (mc *MenuCategory) QueryUser() *UserQuery {
	return NewMenuCategoryClient(mc.config).QueryUser(mc)
}

// Update returns a builder for updating this MenuCategory.
// Note that you need to call MenuCategory.Unwrap() before calling this method if this MenuCategory
// was returned from a transaction, and the transaction was committed or rolled back.
func (mc *MenuCategory) Update() *MenuCategoryUpdateOne {
	return NewMenuCategoryClient(mc.config).UpdateOne(mc)
}

// Unwrap unwraps the MenuCategory entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (mc *MenuCategory) Unwrap() *MenuCategory {
	_tx, ok := mc.config.driver.(*txDriver)
	if !ok {
		panic("ent: MenuCategory is not a transactional entity")
	}
	mc.config.driver = _tx.drv
	return mc
}

// String implements the fmt.Stringer.
func (mc *MenuCategory) String() string {
	var builder strings.Builder
	builder.WriteString("MenuCategory(")
	builder.WriteString(fmt.Sprintf("id=%v, ", mc.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", mc.UserID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(mc.Name)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(mc.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(mc.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// MenuCategories is a parsable slice of MenuCategory.
type MenuCategories []*MenuCategory
