// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Next_Go_App/ent/menucategory"
	"Next_Go_App/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MenuCategoryCreate is the builder for creating a MenuCategory entity.
type MenuCategoryCreate struct {
	config
	mutation *MenuCategoryMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (mcc *MenuCategoryCreate) SetUserID(i int) *MenuCategoryCreate {
	mcc.mutation.SetUserID(i)
	return mcc
}

// SetName sets the "name" field.
func (mcc *MenuCategoryCreate) SetName(s string) *MenuCategoryCreate {
	mcc.mutation.SetName(s)
	return mcc
}

// SetCreatedAt sets the "created_at" field.
func (mcc *MenuCategoryCreate) SetCreatedAt(t time.Time) *MenuCategoryCreate {
	mcc.mutation.SetCreatedAt(t)
	return mcc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (mcc *MenuCategoryCreate) SetNillableCreatedAt(t *time.Time) *MenuCategoryCreate {
	if t != nil {
		mcc.SetCreatedAt(*t)
	}
	return mcc
}

// SetUpdatedAt sets the "updated_at" field.
func (mcc *MenuCategoryCreate) SetUpdatedAt(t time.Time) *MenuCategoryCreate {
	mcc.mutation.SetUpdatedAt(t)
	return mcc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (mcc *MenuCategoryCreate) SetNillableUpdatedAt(t *time.Time) *MenuCategoryCreate {
	if t != nil {
		mcc.SetUpdatedAt(*t)
	}
	return mcc
}

// SetUser sets the "user" edge to the User entity.
func (mcc *MenuCategoryCreate) SetUser(u *User) *MenuCategoryCreate {
	return mcc.SetUserID(u.ID)
}

// Mutation returns the MenuCategoryMutation object of the builder.
func (mcc *MenuCategoryCreate) Mutation() *MenuCategoryMutation {
	return mcc.mutation
}

// Save creates the MenuCategory in the database.
func (mcc *MenuCategoryCreate) Save(ctx context.Context) (*MenuCategory, error) {
	mcc.defaults()
	return withHooks(ctx, mcc.sqlSave, mcc.mutation, mcc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (mcc *MenuCategoryCreate) SaveX(ctx context.Context) *MenuCategory {
	v, err := mcc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mcc *MenuCategoryCreate) Exec(ctx context.Context) error {
	_, err := mcc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mcc *MenuCategoryCreate) ExecX(ctx context.Context) {
	if err := mcc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mcc *MenuCategoryCreate) defaults() {
	if _, ok := mcc.mutation.CreatedAt(); !ok {
		v := menucategory.DefaultCreatedAt()
		mcc.mutation.SetCreatedAt(v)
	}
	if _, ok := mcc.mutation.UpdatedAt(); !ok {
		v := menucategory.DefaultUpdatedAt()
		mcc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mcc *MenuCategoryCreate) check() error {
	if _, ok := mcc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "MenuCategory.user_id"`)}
	}
	if v, ok := mcc.mutation.UserID(); ok {
		if err := menucategory.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "MenuCategory.user_id": %w`, err)}
		}
	}
	if _, ok := mcc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "MenuCategory.name"`)}
	}
	if v, ok := mcc.mutation.Name(); ok {
		if err := menucategory.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "MenuCategory.name": %w`, err)}
		}
	}
	if _, ok := mcc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MenuCategory.created_at"`)}
	}
	if _, ok := mcc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "MenuCategory.updated_at"`)}
	}
	if len(mcc.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "MenuCategory.user"`)}
	}
	return nil
}

func (mcc *MenuCategoryCreate) sqlSave(ctx context.Context) (*MenuCategory, error) {
	if err := mcc.check(); err != nil {
		return nil, err
	}
	_node, _spec := mcc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mcc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	mcc.mutation.id = &_node.ID
	mcc.mutation.done = true
	return _node, nil
}

func (mcc *MenuCategoryCreate) createSpec() (*MenuCategory, *sqlgraph.CreateSpec) {
	var (
		_node = &MenuCategory{config: mcc.config}
		_spec = sqlgraph.NewCreateSpec(menucategory.Table, sqlgraph.NewFieldSpec(menucategory.FieldID, field.TypeInt))
	)
	if value, ok := mcc.mutation.Name(); ok {
		_spec.SetField(menucategory.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := mcc.mutation.CreatedAt(); ok {
		_spec.SetField(menucategory.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := mcc.mutation.UpdatedAt(); ok {
		_spec.SetField(menucategory.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := mcc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   menucategory.UserTable,
			Columns: []string{menucategory.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MenuCategoryCreateBulk is the builder for creating many MenuCategory entities in bulk.
type MenuCategoryCreateBulk struct {
	config
	err      error
	builders []*MenuCategoryCreate
}

// Save creates the MenuCategory entities in the database.
func (mccb *MenuCategoryCreateBulk) Save(ctx context.Context) ([]*MenuCategory, error) {
	if mccb.err != nil {
		return nil, mccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(mccb.builders))
	nodes := make([]*MenuCategory, len(mccb.builders))
	mutators := make([]Mutator, len(mccb.builders))
	for i := range mccb.builders {
		func(i int, root context.Context) {
			builder := mccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MenuCategoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mccb *MenuCategoryCreateBulk) SaveX(ctx context.Context) []*MenuCategory {
	v, err := mccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mccb *MenuCategoryCreateBulk) Exec(ctx context.Context) error {
	_, err := mccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mccb *MenuCategoryCreateBulk) ExecX(ctx context.Context) {
	if err := mccb.Exec(ctx); err != nil {
		panic(err)
	}
}
