// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Next_Go_App/ent/menucategory"
	"Next_Go_App/ent/predicate"
	"Next_Go_App/ent/user"
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MenuCategoryQuery is the builder for querying MenuCategory entities.
type MenuCategoryQuery struct {
	config
	ctx        *QueryContext
	order      []menucategory.OrderOption
	inters     []Interceptor
	predicates []predicate.MenuCategory
	withUser   *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MenuCategoryQuery builder.
func (mcq *MenuCategoryQuery) Where(ps ...predicate.MenuCategory) *MenuCategoryQuery {
	mcq.predicates = append(mcq.predicates, ps...)
	return mcq
}

// Limit the number of records to be returned by this query.
func (mcq *MenuCategoryQuery) Limit(limit int) *MenuCategoryQuery {
	mcq.ctx.Limit = &limit
	return mcq
}

// Offset to start from.
func (mcq *MenuCategoryQuery) Offset(offset int) *MenuCategoryQuery {
	mcq.ctx.Offset = &offset
	return mcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mcq *MenuCategoryQuery) Unique(unique bool) *MenuCategoryQuery {
	mcq.ctx.Unique = &unique
	return mcq
}

// Order specifies how the records should be ordered.
func (mcq *MenuCategoryQuery) Order(o ...menucategory.OrderOption) *MenuCategoryQuery {
	mcq.order = append(mcq.order, o...)
	return mcq
}

// QueryUser chains the current query on the "user" edge.
func (mcq *MenuCategoryQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: mcq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(menucategory.Table, menucategory.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, menucategory.UserTable, menucategory.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(mcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first MenuCategory entity from the query.
// Returns a *NotFoundError when no MenuCategory was found.
func (mcq *MenuCategoryQuery) First(ctx context.Context) (*MenuCategory, error) {
	nodes, err := mcq.Limit(1).All(setContextOp(ctx, mcq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{menucategory.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mcq *MenuCategoryQuery) FirstX(ctx context.Context) *MenuCategory {
	node, err := mcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MenuCategory ID from the query.
// Returns a *NotFoundError when no MenuCategory ID was found.
func (mcq *MenuCategoryQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mcq.Limit(1).IDs(setContextOp(ctx, mcq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{menucategory.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mcq *MenuCategoryQuery) FirstIDX(ctx context.Context) int {
	id, err := mcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MenuCategory entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MenuCategory entity is found.
// Returns a *NotFoundError when no MenuCategory entities are found.
func (mcq *MenuCategoryQuery) Only(ctx context.Context) (*MenuCategory, error) {
	nodes, err := mcq.Limit(2).All(setContextOp(ctx, mcq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{menucategory.Label}
	default:
		return nil, &NotSingularError{menucategory.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mcq *MenuCategoryQuery) OnlyX(ctx context.Context) *MenuCategory {
	node, err := mcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MenuCategory ID in the query.
// Returns a *NotSingularError when more than one MenuCategory ID is found.
// Returns a *NotFoundError when no entities are found.
func (mcq *MenuCategoryQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mcq.Limit(2).IDs(setContextOp(ctx, mcq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{menucategory.Label}
	default:
		err = &NotSingularError{menucategory.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mcq *MenuCategoryQuery) OnlyIDX(ctx context.Context) int {
	id, err := mcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MenuCategories.
func (mcq *MenuCategoryQuery) All(ctx context.Context) ([]*MenuCategory, error) {
	ctx = setContextOp(ctx, mcq.ctx, ent.OpQueryAll)
	if err := mcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MenuCategory, *MenuCategoryQuery]()
	return withInterceptors[[]*MenuCategory](ctx, mcq, qr, mcq.inters)
}

// AllX is like All, but panics if an error occurs.
func (mcq *MenuCategoryQuery) AllX(ctx context.Context) []*MenuCategory {
	nodes, err := mcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MenuCategory IDs.
func (mcq *MenuCategoryQuery) IDs(ctx context.Context) (ids []int, err error) {
	if mcq.ctx.Unique == nil && mcq.path != nil {
		mcq.Unique(true)
	}
	ctx = setContextOp(ctx, mcq.ctx, ent.OpQueryIDs)
	if err = mcq.Select(menucategory.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mcq *MenuCategoryQuery) IDsX(ctx context.Context) []int {
	ids, err := mcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mcq *MenuCategoryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, mcq.ctx, ent.OpQueryCount)
	if err := mcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, mcq, querierCount[*MenuCategoryQuery](), mcq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (mcq *MenuCategoryQuery) CountX(ctx context.Context) int {
	count, err := mcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mcq *MenuCategoryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, mcq.ctx, ent.OpQueryExist)
	switch _, err := mcq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (mcq *MenuCategoryQuery) ExistX(ctx context.Context) bool {
	exist, err := mcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MenuCategoryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mcq *MenuCategoryQuery) Clone() *MenuCategoryQuery {
	if mcq == nil {
		return nil
	}
	return &MenuCategoryQuery{
		config:     mcq.config,
		ctx:        mcq.ctx.Clone(),
		order:      append([]menucategory.OrderOption{}, mcq.order...),
		inters:     append([]Interceptor{}, mcq.inters...),
		predicates: append([]predicate.MenuCategory{}, mcq.predicates...),
		withUser:   mcq.withUser.Clone(),
		// clone intermediate query.
		sql:  mcq.sql.Clone(),
		path: mcq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (mcq *MenuCategoryQuery) WithUser(opts ...func(*UserQuery)) *MenuCategoryQuery {
	query := (&UserClient{config: mcq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mcq.withUser = query
	return mcq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID int `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MenuCategory.Query().
//		GroupBy(menucategory.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (mcq *MenuCategoryQuery) GroupBy(field string, fields ...string) *MenuCategoryGroupBy {
	mcq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MenuCategoryGroupBy{build: mcq}
	grbuild.flds = &mcq.ctx.Fields
	grbuild.label = menucategory.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID int `json:"user_id,omitempty"`
//	}
//
//	client.MenuCategory.Query().
//		Select(menucategory.FieldUserID).
//		Scan(ctx, &v)
func (mcq *MenuCategoryQuery) Select(fields ...string) *MenuCategorySelect {
	mcq.ctx.Fields = append(mcq.ctx.Fields, fields...)
	sbuild := &MenuCategorySelect{MenuCategoryQuery: mcq}
	sbuild.label = menucategory.Label
	sbuild.flds, sbuild.scan = &mcq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MenuCategorySelect configured with the given aggregations.
func (mcq *MenuCategoryQuery) Aggregate(fns ...AggregateFunc) *MenuCategorySelect {
	return mcq.Select().Aggregate(fns...)
}

func (mcq *MenuCategoryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range mcq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, mcq); err != nil {
				return err
			}
		}
	}
	for _, f := range mcq.ctx.Fields {
		if !menucategory.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mcq.path != nil {
		prev, err := mcq.path(ctx)
		if err != nil {
			return err
		}
		mcq.sql = prev
	}
	return nil
}

func (mcq *MenuCategoryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MenuCategory, error) {
	var (
		nodes       = []*MenuCategory{}
		_spec       = mcq.querySpec()
		loadedTypes = [1]bool{
			mcq.withUser != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MenuCategory).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MenuCategory{config: mcq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := mcq.withUser; query != nil {
		if err := mcq.loadUser(ctx, query, nodes, nil,
			func(n *MenuCategory, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (mcq *MenuCategoryQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*MenuCategory, init func(*MenuCategory), assign func(*MenuCategory, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*MenuCategory)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (mcq *MenuCategoryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mcq.querySpec()
	_spec.Node.Columns = mcq.ctx.Fields
	if len(mcq.ctx.Fields) > 0 {
		_spec.Unique = mcq.ctx.Unique != nil && *mcq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, mcq.driver, _spec)
}

func (mcq *MenuCategoryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(menucategory.Table, menucategory.Columns, sqlgraph.NewFieldSpec(menucategory.FieldID, field.TypeInt))
	_spec.From = mcq.sql
	if unique := mcq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if mcq.path != nil {
		_spec.Unique = true
	}
	if fields := mcq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, menucategory.FieldID)
		for i := range fields {
			if fields[i] != menucategory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if mcq.withUser != nil {
			_spec.Node.AddColumnOnce(menucategory.FieldUserID)
		}
	}
	if ps := mcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mcq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mcq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mcq *MenuCategoryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mcq.driver.Dialect())
	t1 := builder.Table(menucategory.Table)
	columns := mcq.ctx.Fields
	if len(columns) == 0 {
		columns = menucategory.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mcq.sql != nil {
		selector = mcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mcq.ctx.Unique != nil && *mcq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range mcq.predicates {
		p(selector)
	}
	for _, p := range mcq.order {
		p(selector)
	}
	if offset := mcq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mcq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MenuCategoryGroupBy is the group-by builder for MenuCategory entities.
type MenuCategoryGroupBy struct {
	selector
	build *MenuCategoryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mcgb *MenuCategoryGroupBy) Aggregate(fns ...AggregateFunc) *MenuCategoryGroupBy {
	mcgb.fns = append(mcgb.fns, fns...)
	return mcgb
}

// Scan applies the selector query and scans the result into the given value.
func (mcgb *MenuCategoryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mcgb.build.ctx, ent.OpQueryGroupBy)
	if err := mcgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MenuCategoryQuery, *MenuCategoryGroupBy](ctx, mcgb.build, mcgb, mcgb.build.inters, v)
}

func (mcgb *MenuCategoryGroupBy) sqlScan(ctx context.Context, root *MenuCategoryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mcgb.fns))
	for _, fn := range mcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mcgb.flds)+len(mcgb.fns))
		for _, f := range *mcgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mcgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mcgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MenuCategorySelect is the builder for selecting fields of MenuCategory entities.
type MenuCategorySelect struct {
	*MenuCategoryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mcs *MenuCategorySelect) Aggregate(fns ...AggregateFunc) *MenuCategorySelect {
	mcs.fns = append(mcs.fns, fns...)
	return mcs
}

// Scan applies the selector query and scans the result into the given value.
func (mcs *MenuCategorySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mcs.ctx, ent.OpQuerySelect)
	if err := mcs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MenuCategoryQuery, *MenuCategorySelect](ctx, mcs.MenuCategoryQuery, mcs, mcs.inters, v)
}

func (mcs *MenuCategorySelect) sqlScan(ctx context.Context, root *MenuCategoryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mcs.fns))
	for _, fn := range mcs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mcs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
